#! /bin/sh

# Variables
foreground_color=$(grep 'FOREGROUND' ~/.config/polybar/colors | awk -F '= ' '{print $2}')
medium_color=$(grep 'MEDIUM' ~/.config/polybar/colors | awk -F '= ' '{print $2}')

# Servicios
killall sxhkd
sxhkd -c ~/.config/sxhkd/sxhkdrc &
killall notification-daemon
killall dunst
dunst -config ~/.config/dunst/dunstrc &
xsetroot -cursor_name redglass &
~/.config/polybar/launchbar &

# BSPC CONFIG
#bspc monitor HDMI-0 -d I II III IV V VI VII VIII IX X

bspc config border_width 1
bspc config window_gap 5
bspc config focused_border_color $foreground_color
bspc config normal_border_color $medium_color
bspc config top_padding 0

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Configuracion de pantalla (Esencial)
#xrandr --output HDMI-0 --mode 1920x1080 --rate 74.97

#AutoStart
picom
testyakuake=$(pgrep -u $uid -x yakuake)
if [ "$testyakuake" == "" ]; then
	yakuake &
fi
feh --bg-fill ~/Pictures/red-kali.png #wallpaper
pulseaudio --start
wmname LGjpeg&
